---
title: "About"
---

## Education

+--------------+-----------------------------------------------------------------------+
| 2020-present | **Emory University**                                                  |
|              |                                                                       |
|              | B.S. Environmental Sciences: Ecology & Conservation; Statistics Minor |
+--------------+-----------------------------------------------------------------------+

## Research Experience

+--------------+-------------------------------------------------------------------------------------------------------------------+
| 2022-present | **Undergraduate Honors Researcher,** Emory University                                                             |
|              |                                                                                                                   |
|              | Advisor: Dr. Carolyn Keogh                                                                                        |
|              |                                                                                                                   |
|              | Habitat use and community ecology in the newly-described Talladega seal salamander (*Desmognathus cheaha*)        |
+--------------+-------------------------------------------------------------------------------------------------------------------+
| May-Aug 2023 | **Hollings Scholar,** Northwest Fisheries Science Center, NOAA/UW SAFS                                            |
|              |                                                                                                                   |
|              | Advisors: Drs. Craig Norrie, Paul McElhany, & Shallin Busch                                                       |
|              |                                                                                                                   |
|              | Physiological responses of diploid and triploid farmed Pacific oysters (*Crassostrea gigas*) to climate stressors |
+--------------+-------------------------------------------------------------------------------------------------------------------+
| 2021-2022    | **Undergraduate Researcher**, Saikawa Laboratory, Emory University                                                |
|              |                                                                                                                   |
|              | Advisor: Dr. Eri Saikawa                                                                                          |
|              |                                                                                                                   |
|              | Soil and stream sediment contamination in the metro-Atlanta area                                                  |
+--------------+-------------------------------------------------------------------------------------------------------------------+
| 2021-2022    | **Undergraduate Researcher,** Dept. of ENVS, Emory University                                                     |
|              |                                                                                                                   |
|              | Advisor: Dr. John Wegner                                                                                          |
|              |                                                                                                                   |
|              | Salamander diversity in university forests and updates to the Emory Forest Management Plan                        |
+--------------+-------------------------------------------------------------------------------------------------------------------+

## Presentations 

(\* - upcoming)

+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2024       | **\*Chang, N.,** K. Jackson, P. McElhany, S. Busch, & C. Norrie. Physiological responses of Pacific oysters (*Crassostrea gigas*) of different ploidy groups to spatial variation in environmental conditions. Ocean Sciences Meeting. New Orleans, LA. Poster presentation.                        |
|            |                                                                                                                                                                                                                                                                                                     |
|            | **\*Chang, N.,** W. Hutchinson, & C. Keogh. Patterns in habitat use of the newly-described Talladega seal salamander (*Desmognathus cheaha*). Society for Integrative & Comparative Biology Annual Meeting. Seattle, WA. Poster presentation.                                                       |
+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2023       | **Chang, N.,** K. Jackson, P. McElhany, S. Busch, & C. Norrie.  Spatial variation in the physiological responses of Pacific oysters (*Crassostrea gigas*) across ploidy groups. National Oceanic & Atmospheric Administration Science & Education Symposium. Silver Spring, MD. Oral presentation.  |
+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2022       | **Chang, N.,** E. Saikawa, T.R. Bowen, L. Fawkes, & F. Sams. Analysis of heavy metals and metalloids in metallurgical slags and stream sediments from the metro-Atlanta area. Emory University Undergraduate Research Summer Symposium. Atlanta, GA. Poster presentation.                           |
+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Grants & Funding

+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2023       | Chen, I., **N. Chang,** & C. Keogh. Okefenokee As Place: Weekend Field Trip to the Okefenokee National Wildlife Refuge. Ecological Society of America SEEDS Chapter Grant. **\$970.**                                          |
|            |                                                                                                                                                                                                                                |
|            | **Chang, N.** & C. Keogh. Investigating habitat use and community dynamics of *Desmognathus sp*. Salamanders in an urban landscape. Emory University Department of Environmental Sciences James G. Lester Fund. **\$1,359.76** |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2021       | **Chang, N.,** C.K. Maki, & J. Wegner. A survey of Agrilus planipennis in Emory University\'s campus forests. Emory University Office of Sustainability Initiatives Incentives Fund. **\$1,050.**                              |
|            |                                                                                                                                                                                                                                |
|            | Maki, C.K., N. Chang, & J. Wegner. Native Pollinator Garden and Campus Reforestation. Emory University Office of Sustainability Initiatives Incentives Fund. **\$2,200.**                                                      |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2020       | **Chang, N.** & J. Horvath. Regreening Complex\'s Green Roof. Emory University Office of Sustainability Initiatives Incentives Fund. **\$300.**                                                                                |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
