---
title: "CV"
---

## Education

+--------------+-----------------------------------------------------------------------+
| 2025-present | **University of Minnesota**                                           |
|              |                                                                       |
|              | Ph.D. Student in Ecology, Evolution, & Behavior                       |
+--------------+-----------------------------------------------------------------------+
| 2020-2024    | **Emory University**                                                  |
|              |                                                                       |
|              | B.S. Environmental Sciences: Ecology & Conservation; Statistics Minor |
+--------------+-----------------------------------------------------------------------+

## Research Interests

-   Ecology, evolution, biogeography, and applied conservation of amphibians and rare plants

-   *Ex situ* conservation and collections-based research at botanical gardens and arboreta

-   Field-based, experiential, and community-engaged learning in ecology, evolution, and environmental science

## Research Experience

+--------------+--------------------------------------------------------------------------------------------------------------------+
| 2025-present | **Graduate Research Assistant,** University of Minnesota                                                           |
|              |                                                                                                                    |
|              | Advisor: Ya Yang                                                                                                   |
|              |                                                                                                                    |
|              | Conservation genomics of imperiled bristleberries (*Rubus* sect. *Setosi*)                                         |
+--------------+--------------------------------------------------------------------------------------------------------------------+
| 2024-2025    | **Research Technician (NSF Rare Plant RaMP),** Atlanta Botanical Garden                                            |
|              |                                                                                                                    |
|              | Advisors: Dr. Lauren Eserman-Campbell, Amanda Carmichael                                                           |
|              |                                                                                                                    |
|              | Phylogenomics to inform species delimitation in the *Sarracenia rubra* complex                                     |
+--------------+--------------------------------------------------------------------------------------------------------------------+
| 2022-2024    | **Undergraduate Honors Researcher,** Emory University                                                              |
|              |                                                                                                                    |
|              | Advisor: Dr. Carolyn Keogh                                                                                         |
|              |                                                                                                                    |
|              | Habitat use and community ecology in the newly-described Talladega seal salamander (*Desmognathus cheaha*)         |
+--------------+--------------------------------------------------------------------------------------------------------------------+
| May-Aug 2023 | **Hollings Scholar,** Northwest Fisheries Science Center, NOAA/UW SAFS                                             |
|              |                                                                                                                    |
|              | Advisors: Drs. Craig Norrie, Paul McElhany, & Shallin Busch                                                        |
|              |                                                                                                                    |
|              | Physiological responses of diploid and triploid farmed Pacific oysters (*Crassostrea gigas*) to climate stressors. |
+--------------+--------------------------------------------------------------------------------------------------------------------+
| 2021-2022    | **Undergraduate Researcher**, Saikawa Laboratory, Emory University                                                 |
|              |                                                                                                                    |
|              | Advisor: Dr. Eri Saikawa                                                                                           |
|              |                                                                                                                    |
|              | Soil and stream sediment contamination in the metro-Atlanta area                                                   |
+--------------+--------------------------------------------------------------------------------------------------------------------+
| 2021-2022    | **Undergraduate Researcher,** Dept. of ENVS, Emory University                                                      |
|              |                                                                                                                    |
|              | Advisor: Dr. John Wegner                                                                                           |
|              |                                                                                                                    |
|              | Salamander diversity in university forests and updates to the Emory Forest Management Plan                         |
+--------------+--------------------------------------------------------------------------------------------------------------------+

## Publications

**Chang, N.,** W. Hutchinson, & C. Keogh. *In press.* Microhabitat use of the Talladega Seal Salamander (*Desmognathus cheaha*) and spatial niche partitioning with a congener in metro-Atlanta headwater streams. *Herpetological Conservation & Biology* 20(2):213-228.

[Preprints]{.underline}

**Chang, N.J.,** L. Eserman-Campbell, A. Carmichael, A.B. Smith, X. Loy, E.E.D. Coffey, & J. Ojcascastro. Ecological niche modeling reveals niche differentiation and climate vulnerability in two imperiled, sympatric Southern Appalachian carnivorous plants. bioRxiv. doi: 10.1101/2025.10.30.685572. In revision for *American Journal of Botany*.

## Selected Presentations

(\* - upcoming)

+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2025   | **Chang, N.,** A. Carmichael, E. Baldwin, J. Leebens-Mack, E.E.D. Coffey, & L. Eserman-Campbell. Species delimitation in the *Sarracenia rubra* species complex to inform conservation actions. Botany 2025. Palm Springs, CA. Oral presentation.                                                                       |
|        |                                                                                                                                                                                                                                                                                                                         |
|        | **Chang, N.,** A. Carmichael, & L. Eserman-Campbell. Species delimitation in the *Sarracenia rubra* species complex to inform conservation actions. Center for Plant Conservation. St. Louis, MO. Poster presentation.                                                                                                  |
+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2024   | **Chang, N.,** A. Carmichael, & L. Eserman-Campbell. Investigating genetic diversity and species delimitation across the *Sarracenia rubra* species complex to inform *ex situ* conservation and reintroductions. Southeastern Partners in Plant Conservation (SePPCon). Atlanta, GA. Poster presentation.              |
|        |                                                                                                                                                                                                                                                                                                                         |
|        | **Chang, N.,** I. Chen, I. Roeske, Y. Covey, K. Coles, M. Chen, C.K. Maki, W. Hutchinson, J. Wegner, & C. Keogh. Community through place: Peer-to-peer mentoring to advance student-led ecological science, practice, and action at Emory University. Ecological Society of America. Long Beach, CA. Oral presentation. |
|        |                                                                                                                                                                                                                                                                                                                         |
|        | **Chang, N.,** W. Hutchinson, & C. Keogh. Patterns in habitat use of the newly-described Talladega seal salamander (*Desmognathus cheaha).* Southeastern Partners in Amphibian & Reptile Conservation. Nauvoo, AL. Speed Talk. [*Winner, **Best Student/Early Career Speed Talk.***]{.underline}                        |
|        |                                                                                                                                                                                                                                                                                                                         |
|        | **Chang, N.,** K. Jackson, P. McElhany, S. Busch, & C. Norrie. Physiological responses of Pacific oysters (*Crassostrea gigas*) of different ploidy groups to spatial variation in environmental conditions. Ocean Sciences Meeting. New Orleans, LA. Poster presentation.                                              |
+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2022   | **Chang, N.,** E. Saikawa, T.R. Bowen, L. Fawkes, & F. Sams. Analysis of heavy metals and metalloids in metallurgical slags and stream sediments from the metro-Atlanta area. Emory University Undergraduate Research Summer Symposium. Atlanta, GA. Poster presentation.                                               |
+--------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Grants & Funding

+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2024    | **Chang, N.** Broadening participation in herp conservation: funding for an undergraduate cohort to attend the 2024 Southeastern Partners in Amphibian & Reptile Conservation meeting. Emory University Dept. of Env. Sciences James G. Lester Fund. **\$3,349.** |
+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2023    | Chen, I., **N. Chang,** & C. Keogh. Okefenokee As Place: Weekend Field Trip to the Okefenokee National Wildlife Refuge. Ecological Society of America SEEDS Chapter Grant. **\$970.**                                                                             |
|         |                                                                                                                                                                                                                                                                   |
|         | **Chang, N.** & C. Keogh. Investigating habitat use and community dynamics of *Desmognathus sp*. Salamanders in an urban landscape. Emory University Department of Environmental Sciences James G. Lester Fund. **\$1,359.76**                                    |
+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2021    | **Chang, N.,** C.K. Maki, & J. Wegner. A survey of Agrilus planipennis in Emory University's campus forests. Emory University Office of Sustainability Initiatives Incentives Fund. **\$1,050.**                                                                  |
|         |                                                                                                                                                                                                                                                                   |
|         | Maki, C.K., N. Chang, & J. Wegner. Native Pollinator Garden and Campus Reforestation. Emory University Office of Sustainability Initiatives Incentives Fund. **\$2,200.**                                                                                         |
+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Teaching Experience

### Graduate Teaching Assistantships

+----------------+--------------------------------------------------------+
| Spring 2025    | Flowering Plant Diversity/World Flora (PMB4511). UMN.  |
+----------------+--------------------------------------------------------+

### Teaching Assistantships

+---------------+----------------------------------------------------------+
| Spring 2023   | Field Botany (ENVS341). Emory University.                |
+---------------+----------------------------------------------------------+
| Fall 2022     | Intro to ENVS Field Studies (ENVS131). Emory University. |
+---------------+----------------------------------------------------------+

## Other Work Experience

+--------------+------------------------------------------------------------------------------------------+
| 2023-2024    | **DEI Program Assistant,** Department of Environmental Sciences, Emory University.       |
+--------------+------------------------------------------------------------------------------------------+
| 2021-2024    | **Resident/Sophomore Advisor,** Office of Residence Life, Emory University, Atlanta, GA. |
+--------------+------------------------------------------------------------------------------------------+
| Mar-Dec 2022 | **Environmental Health & Safety Coordinator,** Saikawa Laboratory, Emory University.     |
+--------------+------------------------------------------------------------------------------------------+
| 2021-2022    | **Intern,** Office of Sustainability Initiatives, Emory University, Atlanta, GA.         |
+--------------+------------------------------------------------------------------------------------------+
| Jun-Aug 2021 | **Environmental Education Intern,** Sensing Nature LLC, Seminole, FL (virtual).          |
+--------------+------------------------------------------------------------------------------------------+

## Service & Leadership

+------------+----------------------------------------------------------------------------------------+
| 2023-2024  | **Waffle Wednesdays Co-Czar,** Dept. of Env. Sciences, Emory University                |
+------------+----------------------------------------------------------------------------------------+
| 2022-2024  | **Diversity, Equity, & Inclusion Committee,** Dept. of Env. Sciences, Emory University |
+------------+----------------------------------------------------------------------------------------+
| 2022-2024  | **Peer Mentor,** Dept. of Environmental Sciences, Emory University                     |
+------------+----------------------------------------------------------------------------------------+
| 2021-2024  | **University Senate Committee on the Environment,** Emory University                   |
|            |                                                                                        |
|            | -   Co-Chair, Forest Management Subcommittee (2022-2024)                               |
|            | -   Undergraduate Representative (2021-2024)                                           |
+------------+----------------------------------------------------------------------------------------+
| 2020-2024  | **Founder & Executive Board,** Emory Ecological Society (ESA SEEDS Chapter)            |
+------------+----------------------------------------------------------------------------------------+
| 2022-2023  | **University Climate Action & Resilience Task Force,** Emory University                |
+------------+----------------------------------------------------------------------------------------+
| 2021-2023  | **Forest Restoration Volunteer,** Fernbank Museum of Natural History                   |
+------------+----------------------------------------------------------------------------------------+
| 2021-2022  | **Organizing Committee,** Symposium on Biological Diversity, Emory University          |
+------------+----------------------------------------------------------------------------------------+

## Continuing Education & Professional Development

+------------+----------------------------------------------------------------------------------------------+
| 2025       | **Applied Plant Conservation Course,** Center for Plant Conservation                         |
+------------+----------------------------------------------------------------------------------------------+
| 2025       | **IUCN Red List Assessor Certification,** International Union for the Conservation of Nature |
+------------+----------------------------------------------------------------------------------------------+

## Honors & Awards

+-----------+--------------------------------------------------------------------------------------------------+
| 2025      | **Honorable Mention - NSF GRFP,** National Science Foundation                                    |
+-----------+--------------------------------------------------------------------------------------------------+
| 2024      | **Boisfeuillet Jones Medal for Servant Leadership,** Emory University                            |
|           |                                                                                                  |
|           | **Elizabeth Long Atwood Undergraduate Research Award,** Emory University Libraries               |
|           |                                                                                                  |
|           | **SEEDS Travel Award to ESA 2024,** Ecological Society of America - SEEDS Program                |
|           |                                                                                                  |
|           | **C. Woodbridge Hickox Award,** Dept. of Environmental Sciences, Emory University                |
+-----------+--------------------------------------------------------------------------------------------------+
| 2023      | **James G. Lester Scholarship,** Department of Environmental Sciences, Emory University          |
|           |                                                                                                  |
|           | **ENVS Conference Travel Award,** Department of Environmental Sciences, Emory University         |
+-----------+--------------------------------------------------------------------------------------------------+
| 2022      | **Ernest F. Hollings Scholarship,** National Oceanic & Atmospheric Administration (NOAA)         |
|           |                                                                                                  |
|           | **UNFCCC COP27 Delegate,** Emory Climate Talks/Dept. of ENVS, Emory University                   |
|           |                                                                                                  |
|           | **Summer Undergraduate Research Experience (SURE) Fellowship,** Emory University                 |
|           |                                                                                                  |
|           | **Robert S. Hascall Sustainability Innovator Award,** Office of Sustainability, Emory University |
|           |                                                                                                  |
|           | **GAEP Scholarship,** Georgia Association of Environmental Professionals                         |
+-----------+--------------------------------------------------------------------------------------------------+
| 2021      | **Eta Sigma Phi Honorary Society for Classical Studies**                                         |
|           |                                                                                                  |
|           | **Jeanne Gold Dean's Achievement Scholarship,** Emory University                                 |
+-----------+--------------------------------------------------------------------------------------------------+
| 2020      | **Kohler Co. Scholarship,** Kohler Co.                                                           |
+-----------+--------------------------------------------------------------------------------------------------+

## Additional Information

-   **Field Skills:** Plant identification; amphibian surveys; incremental soil sampling

-   **Software:** R, ArcGIS Pro

-   **Laboratory Skills:** DNA isolation, genomic library preparation, qPCR, XRF spectrometry, spectrophotometry, titration, respirometry

-   **Languages:** Classical Latin (proficient), German (novice), Middle Egyptian (novice)

-   **Interests:** Hiking, camping, horticulture, aquaria, photography
